# The "Multiple Compose File" feature provides a very powerful way to override
# any configuration in docker-compose.yml without needing to modify
# git-checked-in files since that results in conflicts when upgrading this repo.
# See https://docs.docker.com/compose/extends/#multiple-compose-files for more.

# Just copy this file to `docker-compose.override.yml` and customise it to your liking.
# `cp docker-compose.override.yml.sample docker-compose.override.yml`

# Some example overrides are commented out below. Any uncommented section
# below will automatically override the same section in
# docker-compose.yml when ran with `docker-compose up`.
# See https://docs.docker.com/compose/extends/#adding-and-overriding-configuration for details.

# WARNING: This is for power users only and requires a deep understanding of Docker Compose
# and how the local docker-compose.yml is configured.

services:
  geth:
    # Disable geth
    profiles: [disable]
    # Bind geth internal ports to host ports
    #ports:
      #- 8545:8545 # JSON-RPC
      #- 8551:8551 # AUTH-RPC
      #- 6060:6060 # Metrics

  lighthouse:
    # Disable lighthouse
    profiles: [disable]
    # Bind lighthouse internal ports to host ports
    #ports:
      #- 5052:5052 # HTTP
      #- 5054:5054 # Metrics

  charon:
    networks:
      dvnode:
        aliases:
          - charon-lido
    environment:
      - CHARON_PORT_P2P_TCP=3611
    # Configure any additional env var flags in .env.charon.more
    #env_file: [.env.charon.more]
    # Bind charon internal ports to host ports
    ports:
      #- 3600:3600/tcp # Validator API
      - 3621:3620/tcp # Monitoring

  teku:
    networks:
      dvnode:
        aliases:
          - teku-lido
    # Disable teku
    #profiles: [disable]
    # Bind teku internal ports to host ports
    ports:
      - 8009:8008 # Metrics
    volumes:
      - ./teku/teku_config-lido.yaml:/opt/teku_config.yaml

  prometheus:
    environment:
      - PROM_REMOTE_WRITE_TOKEN=obolhv=ksAph-=HeA28Kpx0OxeTArTWahDcm!us0/sAt1eo!a?gjaM=3btJ1I0dLn9IWIg26w6DM-V=JUGitR46/JZz3QMcWyqp1gNxTlNTUQ-639s2909RNFiSgxGnl
    #volumes:
    #  - ./prometheus/prometheus-obol.yml:/etc/prometheus/prometheus.yml
    # Disable prometheus
    #profiles: [disable]
    # Bind prometheus internal ports to host ports
    #ports:
      #- 9090:9090 # Metrics
    volumes:
      - ./prometheus/prometheus-lido.yml:/etc/prometheus/prometheus.yml

  grafana:
    # Disable grafana
    profiles: [disable]

  #mev-boost:
    # Bind mev-boost internal ports to host ports
    #ports:
      #- 18550:18550 # Metrics

networks:
  dvnode:
    name: obol_dvnode
    external: true
