services:
  geth:
    # Disable geth
    profiles: [disable]
    # Bind geth internal ports to host ports
    #ports:
      #- 8545:8545 # JSON-RPC
      #- 8551:8551 # AUTH-RPC
      #- 6060:6060 # Metrics

  lighthouse:
    # Disable lighthouse
    profiles: [disable]
    # Bind lighthouse internal ports to host ports
    #ports:
      #- 5052:5052 # HTTP
      #- 5054:5054 # Metrics

  charon:
    networks:
      dvnode:
        aliases:
          - charon-alpha
    environment:
      - CHARON_NO_VERIFY=${CHARON_NO_VERIFY:-true}
      - CHARON_BEACON_NODE_ENDPOINTS=https://lighthouse-testnet.swiss-staking.ch
    # Configure any additional env var flags in .env.charon.more
    #env_file: [.env.charon.more]
    # Bind charon internal ports to host ports
    ports:
      #- 3600:3600/tcp # Validator API
      - 3620:3620/tcp # Monitoring

  lodestar:
    networks:
      dvnode:
        aliases:
          - lodestar-alpha
    #profiles: [disable]
    # Bind teku internal ports to host ports
    ports:
      - 5062:5064 # Metrics

  prometheus:
    profiles: [disable]
    #environment:
    #  - PROM_REMOTE_WRITE_TOKEN=obolfwuuu0q5VujsiRq3Nsw5naQuZwQUqfSmSW3k9qXKzpvpG/31cSEau0fk5rMkF=EiKTBdDicbWBAJL6/ZdE!JOKGlqQ6h8iHFqv!Q835K8sWsPlOSOKUY7H4DVDEc
    #volumes:
    # - ./prometheus/prometheus-alpha.yml:/etc/prometheus/prometheus.yml
    # Disable prometheus
    #profiles: [disable]
    # Bind prometheus internal ports to host ports
    #ports:
      #- 9090:9090 # Metrics

  grafana:
    # Disable grafana
    profiles: [disable]

  #mev-boost:
    # Disable mev-boost
    #profiles: [disable]
    # Bind mev-boost internal ports to host ports
    #ports:
      #- 18550:18550 # Metrics